x=('samrat')
y=("samrat")
z=("""samrat
""")
print(x)
print(y)
print(z)
first_name=("raju")
last_name=("rick")
full_name=(first_name+' '+last_name)
print(full_name)
print(full_name.capitalize())
