print("Enter first value")
x=int(input())
print("x:",x)
print("Enter sencond value")
y=int(input())
print("y:",y)
print("x+y",x+y)
print("x-y",x-y)
print("x*y",x*y)
print("x/y",x/y)
print("x//y",x//y)
print("x**y",x**y)
print("x%y",x%y)
